### ISSUE TITLE
本周测试计划：3月2日 - 3月4日

### ISSUE THREAD

**Issue by ShaolongHu** [openthos/testing-analysis#4]
- 测试共4人，每天分别在自己的测试机器上进行multiwindow调研，对比4.4+multiwin和Remix/Phoenix。
- 测试方法：不固定测试方法，所有人每天自行决定测试方法、并记录结果，有必要的话进行截图，每天下午5点开会，整合所有人当天的测试方法和结果，对于没有测到的地方和别人遇到的BUG或疑似BUG，第二天在自己的测试机上补测和验证
- 测试结果：每天在http://36.110.17.43:9001/p/test-multiwin 中增量更新测试结果、测试方法，理论上每天下午6点可看到更新
- 如果在周五前，所有人完成对自己测试机的测试，则转向使用同方台式机的测试
- 周五开会讨论针对multiwindow的调研和适配是否已经足够，如不足下周继续

**Comment by eva980636** [comment]
此周工作 已完成 ，close this issue
