### ISSUE TITLE
本周测试计划 ：3月14日-3月18日 

### ISSUE THREAD

**Issue by ShaolongHu** [openthos/testing-analysis#6]
1. 测试环境（测试专用编译服务器）搭建，有PATCH提交后，测试负责编译验证，调研webhook，联动bugzilla
2. 在真实机器上跑CTS测试，数量上尽量覆盖手头的测试机
3. 学习android下测试框架/工具等，为进一步深入测试做准备。

**Comment by chyyuu** [comment]
我希望大致能够完成：
1 对目前建在实验室内git repo服务器的android repos (based on marshmallow x86最新版，需固定，建立branch，便于回溯)，进行到编译服务器上的本地 sync（开发小组下周可以提交部分更新代码，即使没提交，也可以测试以前的），
　并能在编译服务器上进行编译，如果编译出现错误，可提交到bugzilla和github上（二者建立了自动关联）
2 如果编译通过，再在物理机器上进行
　2.1 启动测试：能够启动到命令行
    2.2 GUI启动测试: 能够启动到图形界面
   ２.3 CTS测试（只选择部分相对关注的，需要指定选择列表），能够在30分钟和1小时完成测试
    2.4 人工测试，测试已有的应用是否能用，如果涉及多窗口，需要测试功能还缺啥，是否有新的bug引入等。

**Comment by eva980636** [comment]
1、由胡少编写，已完成大部分框架，个别细节需细化。
2、明明和晓朝，用模拟器实现以下功能（既将编译出来的IMG或ISO用qemu启动起来，用自动化方法判断是否启动成功.判断是否启动到图形界面。
    刘明明-shell脚本 实现了此功能
    张晓朝-python实现了GUI界面对比。

**Comment by eva980636** [comment]
CTS源码一直未时间看，只遗留这部分内容了。感觉难度应该比较大，JAVA语言毕业后未再使用过
