### ISSUE TITLE
本周测试计划 ：3月21日-3月25日 

### ISSUE THREAD

**Issue by eva980636** [openthos/testing-analysis#7]
1. 根据吴老师已给UI部分 进行分析及讨论（与开发组：陈一璋，罗浩）
2. 编写内存泄漏脚本（六小时不间断打开关闭应用 ，取cpu利用率峰值及物理内存。）
3. 调研monkey,monkeyrunner，实现鼠标点击等界面自动化操作
4. CTS源码学习及分析，看如何只测试关心模块，缩短CTS测试时间 。

**Comment by chyyuu** [comment]
我希望能够在本周完成对openthos的基准版本（基于android-x86-64 5.1 + kernel 4.4）进行功能和稳定性测试（可以只是手工测试）。为此需要注意如下一些问题：
 1 我理解上周还没确定openthos版本（基于上学期的版本）的基准版，目前在哪里？
 2 需要尽早与开发团队协调，目前multiwin团队开发用的基准版是什么？需要明确。避免造成开发版本混乱。
3 基于上学期的openthos版本，为了4月15日的os demo，目前要测试的功能点集合是啥，还有哪些是不足的/缺少的/不稳定的? 可能需要开始准备相关测试文档了。

**Comment by eva980636** [comment]
回复问题
1、目前已确定openthos版本： 基于android-x86-64 5.1 + kernel 4.4
2、今天中线服务器会搭建好-肖络元负责
3、4月15日的os demo，主要测试的功能点是multiwin,systemui.需讨论集生哪些原生应用，需测试哪些第三方应用等 。
